In [1]:
# Required libraries
import requests
from urllib.parse import urlparse
from pathlib import Path
from datetime import datetime
# Required libraries
import tifffile as tiff
import datetime
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
def load_file(fp):
    """Takes a PosixPath object or string filepath
    and returns np array"""
    
    return tiff.imread(fp.__str__())

In [3]:
# List of dates that an observation from Sentinel-2 is provided in the training dataset
dates = [
#     datetime.datetime(2017, 6, 21, 8, 10, 7),
# datetime.datetime(2018,11,9), 
# datetime.datetime(2018,11,14),
# datetime.datetime(2018,11,24),
# datetime.datetime(2018,12,9),
# datetime.datetime(2018,12,14), 
# datetime.datetime(2018,12,19),
# datetime.datetime(2018,12,24),
# datetime.datetime(2018,12,29),   
# datetime.datetime(2019,1,13),
# datetime.datetime(2019,1,23),
# datetime.datetime(2019,2,7),
# datetime.datetime(2019,2,17),
# datetime.datetime(2019,2,22), 
# datetime.datetime(2019,2,27),    
# datetime.datetime(2019,3,4), 
# datetime.datetime(2019,3,9),
# datetime.datetime(2020,1,7), 
# datetime.datetime(2020,1,7), 
# datetime.datetime(2020,5,1)
#     datetime.datetime(2020,10,3)
#     datetime.datetime(2020,12,12)
    datetime.datetime(2020,12,14)
    
    
# datetime.datetime(2020,7,12),  
# datetime.datetime(2020,8,16),  
# datetime.datetime(2020,9,20),  
# datetime.datetime(2020,10,30),
# datetime.datetime(2019,11,5),        
# datetime.datetime(2019,12,15),  
# datetime.datetime(2020,1,19),  
# datetime.datetime(2020,2,28),  
# datetime.datetime(2020,4,3),  
# datetime.datetime(2020,5,8),  
# datetime.datetime(2020,6,12),  
# datetime.datetime(2020,7,17),  
# datetime.datetime(2020,8,21),  
# datetime.datetime(2020,9,25),
# datetime.datetime(2019,11,10),        
# datetime.datetime(2019,12,20)
]

In [4]:
# bands = ['B01', 'B02', 'B03', 'B04', 'B05', 'B06', 'B07', 'B08', 'B8A', 'B09', 'B11', 'B12']
bands = ['B02', 'B03', 'B04', 'B08']

In [25]:
# Sample file to load:
file_name = "data/00/20180215/0_B08_20180215.tif"
# file_name = "data/00/0_label.tif"
# file_name = "data/20170909_imagery_resampled/L2A_T36NXH_20170909T074941_B01_10m-Copy1.tif"
band_data = tiff.imread(file_name)
band_data

array([[64, 64, 64, ..., 63, 63, 67],
       [64, 64, 64, ..., 63, 63, 67],
       [47, 47, 47, ..., 77, 77, 66],
       ...,
       [58, 58, 58, ..., 73, 73, 74],
       [58, 58, 58, ..., 73, 73, 74],
       [61, 61, 69, ..., 73, 73, 69]], dtype=uint8)

In [26]:
band_data.shape

(1999, 1999)

In [27]:
band_data.shape

(1999, 1999)

In [24]:
import rasterio
from rasterio.warp import calculate_default_transform, reproject, Resampling
import os

In [25]:
# band_data_ = rasterio.open(file_name)
# print (band_data_.crs)

In [26]:
# expRst = rasterio.open(file_name)
# expRst.crs

In [75]:
for tile in range(1):
    fids = f'data/00/field_id.tif'
    expRst = rasterio.open(fids)
    print (expRst.crs)

EPSG:32636


In [76]:
band_data = tiff.imread(fids)
band_data

array([[       0,        1,        2, ...,     3367,     3368,     3369],
       [    3370,     3371,     3372, ...,     6737,     6738,     6739],
       [    6740,     6741,     6742, ...,    10107,    10108,    10109],
       ...,
       [14315760, 14315761, 14315762, ..., 14319127, 14319128, 14319129],
       [14319130, 14319131, 14319132, ..., 14322497, 14322498, 14322499],
       [14322500, 14322501, 14322502, ..., 14325867, 14325868, 14325869]],
      dtype=int32)

In [77]:
band_data.shape

(4251, 3370)

In [78]:
for tile in range(1):
    fids = f'data/00/field_id.tif'
#     labs = f'./data/0{tile}/{tile}_label.tif'
    fid_arr = load_file(fids)
#     lab_arr = load_file(labs)

In [79]:
fid_arr.shape

(4251, 3370)

In [80]:
import numpy as np

In [81]:
len(np.unique(fid_arr.flatten()))

14325870

In [82]:
fid_arr[0]

array([   0,    1,    2, ..., 3367, 3368, 3369], dtype=int32)

In [83]:
import pandas as pd

In [84]:
# NOTE: Code slice being replaced has col_loc starting at 1 and fid starting at 1
df = pd.DataFrame(
    list(np.ndindex((fid_arr.shape[0],
    fid_arr.shape[1]))), columns =['row_loc', 'col_loc']
)
df["fid"] = fid_arr.flatten().astype(int)
df["tile"] = 0
print(len(df))
print(df.head())

14325870
   row_loc  col_loc  fid  tile
0        0        0    0     0
1        0        1    1     0
2        0        2    2     0
3        0        3    3     0
4        0        4    4     0


In [85]:
print(len(df))
print(df.groupby('fid').count().shape)
print(df.columns)
df.head()

14325870
(14325870, 3)
Index(['row_loc', 'col_loc', 'fid', 'tile'], dtype='object')


row_loc  col_loc  fid  tile
0        0        0    0     0
1        0        1    1     0
2        0        2    2     0
3        0        3    3     0
4        0        4    4     0

In [86]:
tile = 0
d = datetime.datetime(2019,11,27)

print(str(d))
t = '0' + str(tile)
for b in bands: # 3) For each band
    print(b,  d.strftime("%m%d%Y"))
    col_name = d.strftime("%Y%m%d") + '_' + b

    # if tile == 0:
    # If the column doesn't exist, create it and populate with 0s
    if col_name not in df.columns:
        df[col_name] = 0

#             Load im
    try:
        im = load_file(f"data/{t}/{d.strftime('%Y%m%d')}/{t[1]}_{b}_{d.strftime('%Y%m%d')}.tif")
        print(f"__________{im.shape}")
    except FileNotFoundError:
        continue

    # NOTE: Pixel values are added accoriding to tile position in original.
    # Since it's one tile, df.loc[df.tile == tile][['row_loc', 'col_loc']].values
    # will return all row_loc and col_loc ptns of the df. so im.flatten and assign can replace this
    df[col_name] = im.flatten().astype(int)

2019-11-27 00:00:00
B02 11272019
__________(4251, 3370)
B03 11272019
__________(4251, 3370)
B04 11272019
__________(4251, 3370)
B08 11272019
__________(4251, 3370)


In [87]:
df.head()

row_loc  col_loc  fid  tile  20191127_B02  20191127_B03  20191127_B04  \
0        0        0    0     0             0             0             0   
1        0        1    1     0             0             0             0   
2        0        2    2     0             0             0             0   
3        0        3    3     0             0             0             0   
4        0        4    4     0             0             0             0   

   20191127_B08  
0             0  
1             0  
2             0  
3             0  
4             0

In [88]:
# import pandas as pd
# df = pd.read_csv('Trias_data_20200207.csv')

In [89]:
df1 = df.query('fid > 2000000')
# new_df.to_csv('NDVI_mean_Classification_aoi5.csv')
df1.head()

row_loc  col_loc      fid  tile  20191127_B02  20191127_B03  \
2000001      593     1591  2000001     0            10            18   
2000002      593     1592  2000002     0            10            18   
2000003      593     1593  2000003     0            11            20   
2000004      593     1594  2000004     0            10            20   
2000005      593     1595  2000005     0            11            18   

         20191127_B04  20191127_B08  
2000001            21            60  
2000002            21            60  
2000003            24            62  
2000004            23            63  
2000005            23            60

In [90]:
df.to_csv('Farm_Africa_data_20191127.csv', index=False)